/usr/bin/time -l ./target/release/probmap index -g ../gtdbtest -m ../meta_single_test.tsv -k 10 | grep "Number of kmers:" >> test
/usr/bin/time -l ./target/release/probmap index -g ../gtdbtest -m ../meta_single_test.tsv -k 11 | grep "Number of kmers:" >> test
/usr/bin/time -l ./target/release/probmap index -g ../gtdbtest -m ../meta_single_test.tsv -k 12 | grep "Number of kmers:" >> test
/usr/bin/time -l ./target/release/probmap index -g ../gtdbtest -m ../meta_single_test.tsv -k 13 | grep "Number of kmers:" >> test
/usr/bin/time -l ./target/release/probmap index -g ../gtdbtest -m ../meta_single_test.tsv -k 14 | grep "Number of kmers:" >> test
/usr/bin/time -l ./target/release/probmap index -g ../gtdbtest -m ../meta_single_test.tsv -k 15 | grep "Number of kmers:" >> test
/usr/bin/time -l ./target/release/probmap index -g ../gtdbtest -m ../meta_single_test.tsv -k 16 | grep "Number of kmers:" >> test
/usr/bin/time -l ./target/release/probmap index -g ../gtdbtest -m ../meta_single_test.tsv -k 17 | grep "Number of kmers:" >> test
/usr/bin/time -l ./target/release/probmap index -g ../gtdbtest -m ../meta_single_test.tsv -k 18 | grep "Number of kmers:" >> test
/usr/bin/time -l ./target/release/probmap index -g ../gtdbtest -m ../meta_single_test.tsv -k 19 | grep "Number of kmers:" >> test
/usr/bin/time -l ./target/release/probmap index -g ../gtdbtest -m ../meta_single_test.tsv -k 20 | grep "Number of kmers:" >> test
/usr/bin/time -l ./target/release/probmap index -g ../gtdbtest -m ../meta_single_test.tsv -k 25 | grep "Number of kmers:" >> test
/usr/bin/time -l ./target/release/probmap index -g ../gtdbtest -m ../meta_single_test.tsv -k 32 | grep "Number of kmers:" >> test
